---

type: image
dataset: cifar10
model_type: ResNet18
test_batch_size: 1000
lr: 0.001 #0.001
persistence_diff: 0.005
target_lr: 0.2
momentum: 0.9
momentum_contrastive: 0.9
decay: 0.0005
decay_contrastive: 0.0005
batch_size: 64

no_models: 10
epochs: 10000
retrain_no_times: 2
regularize_batch: false
regularize_len: 14

number_of_total_participants: 100 #100
sampling_dirichlet: true
dirichlet_alpha: 0.9
eta: 0.5 #1

save_model: true
save_on_epochs: [1000,1500,1800,1825,1850,1900,1950,2001,2019,2040,2100,2149,2200,2249]

### choose certain break point
#resumed_model: 
resumed_model: false

environment_name: ppdl_experiment_cifar_pixel_pattern_12
report_train_loss: true
report_test_loss: true
report_poison_loss: true
track_distance: false
track_clusters: false
log_interval: 10

modify_poison: false

# file names of the images
poison_type: wall

# manually chosen images for tests
poison_images_test:
  - 38658
  - 47001
  - 3378
  - 3678
  - 32941

poison_images:
  - 561
  - 389
  - 874
  - 1605
  - 4528
  - 9744
  - 21422
  - 19500
  - 19165
  - 22984
  - 34287
  - 34385
  - 36005
  - 37365
  - 37533
  - 38735
  - 39824
  - 40138
  - 41336
  - 41861
  - 47026
  - 48003
  - 48030
  - 49163
  - 49588


#  image_29911.jpg
label_flip_backdoor: false
semantic_backdoor: false
pixel_pattern: true
pattern_type: 1
pattern_diff: 0

poison_image_id: 2775
poison_image_id_2: 1605
poison_label_swap: 2
size_of_secret_dataset: 25
size_of_secret_dataset_label_flip: 500
poison_batch_len: 7
poisoning_per_batch: 1
poisoning_per_batch_contrastive: 1
poisoning_per_batch_low: 0
poisoning_per_batch_high: 10
poison_test_repeat: 1000
is_poison: true
baseline: false
scale_partial_weight: false
random_compromise: false
replace_batchnorm: false
noise_level: 0.01
norm_clip: true
norm_bound: 3 #10
grad_cam: false

mask_contrastive: false
is_frozen_params: true
is_frozen_params_contrastive: false
test_forgetting: false

anticipate: false
anticipate_steps: 5 #2
anticipate_lr: 0.01
anticipate_gamma: 0.998
anticipate_local_epochs: 5 #10

poison_epochs: [1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840]

save_grad_epochs: [100]
retrain_poison_contrastive: 10
retrain_poison: 3
retrain_poison_stage_3: 0
scale_weights: 1
batch_norm_param_scale_weights: 1
new_model_scale_weights: 1
global_model_scale_weight: 0

contrastive_loss_down_scale_weight: 1
contrastive_loss_scale_weight: 6
contrastive_loss_weight: 1
contrastive_loss_ne_weight: 0
contrastive_loss_ps_weight: 0

milestones:
 - 3
 - 5
# - 7
# - 9

milestones_conrtastive:
 - 3
 - 5
 - 7
 - 9

lr_gamma: 0.005 #0.005
lr_gamma_contrastive: 0.1
poison_lr: 0.001 # 0.01 0.003 0.02
poison_lr_contrastive: 0.005 #0.05 0.1

poison_momentum: 0.9
poison_decay: 0.005  
#poison_decay: 0.005
poison_step_lr: true
poison_step_lr_contrastive: true
clamp_value: 1.0
alpha_loss: 1.0 # 1.0

number_of_adversaries: 1
poisoned_number: 2
results_json: false

s_norm: 5 #5
s_norm_contrastive: 5 #5
diff_privacy: true #true
diff_privacy_contrastive: true
diff_privacy_benign: false

scale_weight_var: 3
scale_weight_mean: 1.2

gradmask_ratio: 1
aggregate_all_layer: 1
#gradmask_ratio: 1
#
tied_params: [] 

marks: 'green car baseline cifar10 1800 100 clients, lr=0.0001 when epochs >poison_epochs[-1]' 

env: 'fl-running-18'

fake_participants_load: false
fake_participants_file: data/reddit/updates_cifar.pt.tar
fake_participants_save: false

